web/apps/parametro/urls.py
from django.urls import path
from .views import (ParametroListView, ParametroDetailView,
                    ParametroCreateView, ParametroUpdateView,
                    ParametroDeleteView)

from .views import (AppView)

app_name = 'parametro'

urlpatterns = [
    path("app/", AppView.as_view(), name="application"),
    path("listar/", ParametroListView.as_view(), name="list"),
    path("crear/", ParametroCreateView.as_view(), name="create"),
    path("modificar/<int:id>/", ParametroUpdateView.as_view(), name="update"),
    path("ver/<slug:nombre>/", ParametroDetailView.as_view(), name="detail"),
    path("borrar/<int:id>/", ParametroDeleteView.as_view(), name="delete"),
]

"""


"""

web/web/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('filer/', include('filer.urls')),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path('accounts/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('parametro/',
         include('apps.parametro.urls', namespace='parametro'),
         name='parametro'),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/apps/parametro/models.py
from django.db import models
from apps.icono.models import Icono
from autoslug import AutoSlugField
from django.urls import reverse


class Parametro(models.Model):
    DEFAULT = "SB"
    TIPOS_CHOICES = {
        (DEFAULT, "subjetiva"),
        ("OB", "objetiva"),
    }
    tipo = models.CharField(max_length=10,
                            choices=TIPOS_CHOICES,
                            default=DEFAULT)
    nombre = models.CharField(max_length=100)
    unidad_medida = models.CharField(max_length=10)
    slug = AutoSlugField(populate_from='nombre')
    descripcion = models.TextField()
    icono = models.ForeignKey(Icono,
                              related_name='parametros',
                              on_delete=models.SET_NULL,
                              null=True,
                              blank=True)

    class Meta:
        app_label = "parametro"
        verbose_name = "Parámetro"
        verbose_name_plural = "Parámetros"
        ordering = ("nombre", )

    def natural_key(self):
        return (self.slug_nombre, )

    def get_absolute_url(self):
        return reverse('parametro:detail',
                       kwargs={
                           'nombre': self.slug,
                       })

    def __str__(self):
        return f"{self.nombre}@{self.tipo}@{self.unidad_medida}"

web/apps/parametro/forms.py
from django.forms import ModelForm
from .models import Parametro
from django import forms


class ParametroForm(ModelForm):
    class Meta:
        model = Parametro
        fields = [
            "tipo",
            "nombre",
            "unidad_medida",
            "descripcion",
            "icono"
        ]
        widgets = {
            "tipo": forms.RadioSelect()
        }

web/apps/parametro/views.py
from django.views.generic import (
    CreateView, DeleteView,
    UpdateView, ListView,
    DetailView, TemplateView)
from .forms import ParametroForm
from .models import Parametro
from apps.home.views import menu_nav
from django.http import HttpResponse, HttpResponseRedirect


from files.functions.links import LinkData


def app_menu():
    menu = {
        "Parámetro": [
            LinkData("Listar",
                     "parametro:list",
                     model="parametro",
                     perms=["view"]),
            LinkData("Crear",
                     "parametro:create",
                     model="parametro",
                     perms=["add"]),
        ],
    }
    return menu


class BaseView:
    app_active = 'parametro'

    def context_data(self, *args, **kwargs):
        kwargs.update({
            'menu_nav': menu_nav,
            "app_menu": app_menu,
            "app_active": self.app_active,
            "menu": True,
        })
        return kwargs


class AppView(TemplateView, BaseView):
    template_name = 'parametro/app.dj.html'

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs["action"] = "Crear"
        kwargs.update(self.context_data())
        return kwargs


class ParametroListView(ListView, BaseView):
    model = Parametro
    template_name = 'parametro/list.dj.html'

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs["action"] = "Crear"
        kwargs.update(self.context_data())
        return kwargs


class ParametroDetailView(DetailView, BaseView):
    model = Parametro
    template_name = 'parametro/detail.dj.html'
    slug_field = 'slug'
    slug_url_kwarg = 'nombre'

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs.update(self.context_data())
        return kwargs


class ParametroCreateView(CreateView, BaseView):
    model = Parametro
    template_name = 'parametro/create.dj.html'
    form_class = ParametroForm

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs["action"] = "Crear"
        kwargs.update(self.context_data())
        return kwargs


class ParametroUpdateView(UpdateView, BaseView):
    model = Parametro
    template_name = 'parametro/update.dj.html'
    form_class = ParametroForm

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs["action"] = "Actualizar"
        return kwargs


class ParametroDeleteView(DeleteView, BaseView):
    model = Parametro
    template_name = 'parametro/delete.dj.html'

web/apps/parametro/templates/parametro/.#form.dj.html
david@pineiden.5116:1613179057

web/apps/parametro/templates/parametro/app.dj.html
{% extends "parametro/base.dj.html" %}

{% block content_parametro %}
<ul>
    <li>Listar</li>
    <li>Buscar</li>
    <li>Administrar</li>
    <li>Favoritos</li>
    <li>Crear</li>
</ul>
{% endblock%}

web/apps/parametro/templates/parametro/base.dj.html
{% extends "base.dj.html" %}
{% load static %}

{% block title %}
Parametros | {{SITE_NAME}}
{% endblock %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'parametro:application' %}">Parametro</a>
</li>
{% endblock breadcrumbs %}

{% block content_article %}
<div class="tile is-ancestor">
    <div class="tile is-parent is-2">
        {% block sidebar_left %}
        <aside class="sticky tile is-child box">
            {% include 'parametro/menu.dj.html' %}
        </aside>
        {% endblock sidebar_left %}
    </div>

    <div class="tile is-parent">
        <div class="tile is-child box">
            {% block content_parametro %}
            {% endblock%}
        </div>
    </div>
</div>
{% endblock%}

web/apps/parametro/templates/parametro/create.dj.html
{% extends "parametro/base.dj.html" %}

{% block content_parametro %}
{% include 'parametro/form.dj.html' %}
{% endblock%}

web/apps/parametro/templates/parametro/detail.dj.html
{% extends "parametro/base.dj.html" %}

{% block content_parametro %}
<h1 class="title">{{object.nombre}}</h1>
<figure><img src="{{object.icono.archivo.url}}" width="100px"></figure>
<section>{{object.descripcion}}</section>

{% endblock%}

web/apps/parametro/templates/parametro/form.dj.html
{% load widget_tweaks %}
{% load static %}

<form action="{{request.get_full_path|safe}}" enctype="multipart/form-data"
      method="post" id="member_form" class="django form">
    {% csrf_token %}
    <!-- tipo: radio button -->
    <div class="field" id="tipo-parametro">
            {% for key, tipo in form.tipo.field.choices %}
        <label class="radio">
            <input type="radio" name="tipo" value="{{key}}">{{tipo}}
        </label>
        {% endfor %}
    </div>

    <!-- nombre : input -->
    <div  class="field" id="field_nombre">
        <label class="label"
               for="{{form.nombre.id_for_label}}">
            {{form.nombre.label}}
        </label>
        <div class="control">
                {% render_field form.nombre class+="input is-medium" %}
        </div>
        <span class="help is-invalid">{{ form.nombre.errors }}</span>
    </div>
    <!-- unidad_medida -->
    <div  class="field" id="field_unidad_medida">
        <label class="label"
               for="{{form.unidad_medida.id_for_label}}">
            {{form.unidad_medida.label}}
        </label>
        <div class="control">
            {% render_field form.unidad_medida class+="input is-medium" %}
        </div>
        <span class="help is-invalid">{{ form.unidad_medida.errors }}</span>
    </div>
    <!-- descripcion -->
    <div  class="field" id="field_descripcion">
        <label class="label"
               for="{{form.descripcion.id_for_label}}">
            {{form.descripcion.label}}
        </label>
        <div class="control">
            {% render_field form.descripcion class+="textarea is-medium" %}
        </div>
        <span class="help is-invalid">{{ form.descripcion.errors }}</span>
    </div>
    <!-- icono -->
    <div  class="field" id="field_icono">
        <label class="label"
               for="{{form.icono.id_for_label}}">
            {{form.icono.label}}
        </label>
        <div class="control">
            {% render_field form.icono class+="select is-medium" %}
        </div>
        <span class="help is-invalid">{{ form.icono.errors }}</span>
    </div>
    <!-- botones de acción -->
    <div class="buttons are-medium columns">
        <div class="column">
            <button type="submit"
                    class="button is-primary is-fullwidth">
                {{action}}</button>
        </div>
        <div class="column">
            <a class="button is-warning is-fullwidth" href="{% if group %}
                      "{% url 'parametro:detail' object.slug %}"
               {% else %}
               {% url 'parametro:list' %}{% endif %}">
                Cancelar</a>
        </div>
    </div>
</form>

web/apps/parametro/templates/parametro/list.dj.html
{% extends "parametro/base.dj.html" %}
{% load static %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'parametro:list' %}">Lista de Parametros</a>
</li>
{% endblock breadcrumbs %}

<!-- lista de parametros creados -->
{% block content_parametro %}
<div class="tile is-child">
    <h2 class="title is-2">
        <i class="fa fa-groups-manager-group"></i> Parametros
    </h2>
</div>
<div class="tile is-child">
<table class="table is-hoverable is-fullwidth is-striped" id="clasification_list">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th class="has-text-right">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for parametro in object_list %}
        <tr class="">
            <td class=""><a href="{{parametro.get_absolute_url}}">{{parametro.nombre}}</a></td>
            <td class="">{{parametro.descripcion}}</td>
            <td class="is-horizontal">
                <!--PERMISSIONS_HERE-->
                {% if perms.groups_manager.can_change_project %}
                <a href="{% url 'parametro:update' parametro.id %}" class="button is-warning is-small is-block">
                    <i class="fa fa-edit"></i>
                </a>
                {% endif %}
                {% if perms.groups_manager.can_delete_project %}
                <a href="{% url 'parametro:delete' parametro.id %}"
                   class="button is-danger is-small is-block">
                    <i class="fa fa-times"></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

{% endblock %}

web/apps/parametro/templates/parametro/menu.dj.html
{{menu_title}}
{% for app, group in app_menu.items %}
{{app}}
<ul>
    {% for elem in group %}
    <li>{{elem.html|safe}}</li>
    {% endfor %}
</ul>
{% endfor %} 