web/apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (AppAccountsView, RegistrarUsuario, activate,
                    activation_sent_view, status_task_signup, LoginView,
                    ProfileView, LogoutView, PasswordChangeView,
                    PasswordChangeDoneView, profile_update_field)
from django.urls import reverse, reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('', AppAccountsView.as_view(), name='application'),
    path('app', AppAccountsView.as_view(), name='application'),
    path('login/', LoginView.as_view(), name='login'),
    path(
        'logout',
        LogoutView.as_view(),  # not override template
        name='logout'),
    path('password_change',
         PasswordChangeView.as_view(
             template_name="registration/password_change.dj.html",
             extra_context={'menu': True}),
         name='password_change'),
    path('password_change/done',
         PasswordChangeDoneView.as_view(
             template_name="registration/password_change_done.dj.html",
             extra_context={'menu': True}),
         name='password_change_done'),
    path('password_reset',
         auth_views.PasswordResetView.as_view(
             template_name="registration/password_reset.dj.html",
             email_template_name="registration/password_reset_email.dj.html",
             html_email_template_name="registration/password_reset_email.dj.html",
             subject_template_name="registration/password_reset_subject.txt",
             success_url=reverse_lazy("accounts:password_reset_done"),
             extra_context={'menu': True}),
         name='password_reset'),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(
             template_name="registration/password_reset_done.dj.html",
             extra_context={'menu': True}),
         name='password_reset_done'),
    path('password-reset/confirm/uidb64=<uidb64>/token=<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.dj.html',
             success_url=reverse_lazy('accounts:password_reset_complete'),
             extra_context={'menu': True}),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.dj.html',
             extra_context={'menu': True}),
         name='password_reset_complete'),
    path("signup/", RegistrarUsuario.as_view(), name='signup'),
    path('activacion-enviada/task=<task_code>',
         activation_sent_view,
         name='activacion-enviada'),
    path('activar/uidb64=<uidb64>/token=<token>/', activate, name='activate'),
    path("ajax/status_task/task=<str:task_id>",
         status_task_signup,
         name="status_task"),
    path("perfil/", ProfileView.as_view(), name='profile'),
    path("perfil/usuario=<str:username>",
         ProfileView.as_view(),
         name='profile_user'),
    path("perfil/update_field/usuario=<str:username>",
         profile_update_field,
         name='profile_update_field'),
]

web/apps/home/urls.py
from django.conf.urls import url
from django.urls import path
# from django.contrib import admin
from apps.home import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('nosotros', views.NosotrosView.as_view(), name='nosotros'),
    path('aplicaciones', views.AppsView.as_view(), name='apps'),
    #path('proyecto', views.ProyectoView.as_view(), name='proyecto'),
    #path('contacto', views.ContactoView.as_view(), name='contacto'),
]

web/web/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('filer/', include('filer.urls')),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path('accounts/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('parametro/',
         include('apps.parametro.urls', namespace='parametro'),
         name='parametro'),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/files/templates/base.dj.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}

<html class="has-navbar-fixed-top"> 

    <!doctype html>
    <!--[if lt IE 7]>
        <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
    <!--[if IE 7]>
        <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
    <!--[if IE 8]>
        <html class="no-js lt-ie9" lang=""> <![endif]-->
    <!--[if gt IE 8]><!-->
        <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
            <title>{% block title %}{% endblock %}</title>
            <meta name="description" content="">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="shortcut icon"
                  href="{% static 'img/icon.png' %}"
                  type="image/svg+xml" sizes="any">

            <!-- bloque llamada a estáticos principal -->
            {% block top_front_frameworks %}
            <link rel="stylesheet"
                  type="text/css"
                  href="{% static 'css/principal.css' %}">
            <link rel="stylesheet"
                  type="text/css"
                  href="{% static 'css/menu_nav.css' %}">
            <link rel="stylesheet"
                  type="text/css"
                  href="{% static 'css/footer.css' %}">
            {% endblock %}


            <!-- Bloque para añadir css extras en header -->
            {% block head_css %}
            <!-- Bulma, rxjs, d3, openalayers personalization CSS -->
            <link rel="stylesheet"
                  type="text/css"
                  href="{% static 'adaluna/dist/index.css' %}">

            {% endblock %}

            <!-- Bloque para añadir js extra en header-->
            {% block head_javascript %}
            <!-- Bulma, rxjs, d3, openalayers personalization JS -->
            <script defer
                    src="{% static 'adaluna/dist/index.js' %}"></script>
                        

            <script defer
                    src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

            {% endblock %}

            {% block special_css %}

            {% endblock %}

        </head>

        <body>
            <!-- Ubicación de encabezado del contenido -->
            {% include 'menu_nav.dj.html' %}

            <div id="show_content">

                <div id="hero">
                    {% block hero_content %}
                    {% endblock %}
                </div>

            <main id="all_content
                      {% block main_tag_id %}
                      {% endblock main_tag_id %}"
                  class="container">
                <div class="tile is-parent">
                    <div class="tile is-child box">
                <nav class="breadcrumb" aira-label="breadcrumbs">
                    <ul>
                        {% block breadcrumbs %}
                        {% endblock breadcrumbs %}
                    </ul>
                </nav>
                    </div>
                </div>
                {% block content_article %}
                {% endblock content_article %}
            </main>
           </div>


            <!-- Elemento Inferior dentro de bloque body-->
           <footer class="footer has-background-otoño">
               <!-- cargar el html de la zona de contacto -->
               <div class="container">
                <div class="columns">
                    <div class="column">
                        {% include 'contacto.dj.html' %}
                    </div>
                    <div class="column"></div>
                </div>
               </div>

               <!-- block to load framework -->
               {% block buttom_front_frameworks %}
               {% endblock %}

               <!-- Añadir CSS Extra en footer -->
                {% block footer_css %}
                {% endblock %}

                <!-- Añadir JS extra en footer -->
                {% block footer_javascript %}
               {% endblock %}
               <script>
                document.addEventListener('DOMContentLoaded', () => {

                    // Get all "navbar-burger" elements
                    const $navbarBurgers = Array.prototype.slice.call(
                        document.querySelectorAll('.navbar-burger'), 0);

                    // Check if there are any navbar burgers
                    if ($navbarBurgers.length > 0) {

                        // Add a click event on each of them
                        $navbarBurgers.forEach( el => {
                            el.addEventListener('click', () => {

                                // Get the target from the "data-target" attribute
                                const target = el.dataset.target;
                                const $target = document.getElementById(target);

                                // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                                el.classList.toggle('is-active');
                                $target.classList.toggle('is-active');

                            });
                        });
                    }

                });
               </script>
               <style>
               </style>
                <footer>

        </body>

    </html>

web/files/templates/contacto.dj.html
<section class="mdl-mini-footer__left-section">
    <a href="/contacto">Contáctanos</a>
</section>

<section class="mdl-mini-footer__middle-section">
    <p>Realizado con:</p>
    <ol>
        <li><a href="https://www.djangoproject.com/">Django
            Framework</a></li>
        <li>el sistema operativo <a
                                     href="https://www.debian.org/index.es.html">GnuLinux
            Debian</a></li>
        <li><a href="https://bulma.io">Bulma CSS, Framework</a></li>
    </ol>
</section>

<section class="mdl-mini-footer__right-section">
    <p>Este proyecto es <a href="https://endefensadelsl.org/manifiesto_telecomunista.html"> CopyFarleft</a> + GPLv3</p>
    <a href="https://gitlab.com/pineiden/web-curso-programacion">Descarga el Código
    Fuente de esta Web</a>
</section>

web/files/templates/menu_nav.dj.html
{% load static %}
<nav class="navbar is-fixed-top is-purpura" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'home:index' %}">
            <img src="{% static 'img/logo.jpg' %}"
                 style="width:40px;height:auto;"/>
        </a>
        <a role="button" class="navbar-burger" aria-label="menu"
           aria-expanded="false" data-target="navMenu">
            <span aria-hidden="true">
            </span>
            <span aria-hidden="true">
            </span>
            <span aria-hidden="true">
            </span>
        </a>
    </div>
        <div class="navbar-menu" id="navMenu">
            <div class="navbar-start">
            {% for item in menu_nav %}
            {{item.html|safe}}
            {% endfor %}
            </div>
            <div class="navbar-end">
            {% if not user.is_authenticated %}
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-cielo"  href="{% url 'accounts:login' %}">
                            <strong>Ingresar</strong>
                        </a>
                        <a class="button is-turquesa"  href="{% url 'accounts:signup' %}">
                            <strong>Registrarse</strong>
                        </a>
                    </div>
                </div>
            {% else %}
            <div class="buttons">
                {% if user.is_superuser %}
                <a class="button is-link"  href="{% url 'admin:index' %}">
                    <strong>Administrar</strong>
                </a>
                {% endif %}
                <a class="button is-primary"  href="{% url 'accounts:profile_user' username=user.username %}">
                    <strong>Perfil</strong>
                </a>
                <a class="button is-danger"  href="{% url 'accounts:logout' %}">
                    <strong>Salir</strong>
                </a>

            </div>
            {% endif %}
            </div>
        </div>
 </nav>

web/files/templates/menu_nav_drawer.dj.html
<nav class="mdl-navigation drawer">
	  <a  class="mdl-navigation__link" title="Inicio" href="/">Inicio</a>
	  <a  class="mdl-navigation__link" title="El Curso" href="/pagina/el-curso">El Curso</a>
	  <a  class="mdl-navigation__link" title="Nosotros" href="/pagina/nosotros">Nosotros</a>
	  <a  class="mdl-navigation__link" title="Inscribirse" href="/inscripcion/{{SLUG_TITULO}}/{{SLUG_GENERACION}}">Inscribirse</a>
	  <a  class="mdl-navigation__link" title="Contacto" href="#">Contacto</a>
</nav>

web/files/templates/share_menu.dj.html
{% load social_share %}

<div class="dropdown-menu" id="dropdown-share" role="menu">
    <div class="dropdown-content"> 
        <div class="dropdown-item">
            <button class="button is-link is-outlined">
            <span class="icon is-small">
                <i class="fab fa-facebook"></i>
            </span><span>{% post_to_facebook data.url "facebook" %}</span>
            </button>
        </div>
        <div class="dropdown-item">
            <button class="button is-link is-outlined">
                <span class="icon is-small">
                    <i class="fab fa-google-plus"></i>
                </span>
                <span>
                    {% post_to_gplus  data.url  "google+" %}
                </span>
            </button>
                
        </div>
        <div class="dropdown-item">
            <button class="button is-link is-outlined">
                <span class="icon is-small">
                    <i class="fab fa-twitter"></i>
                </span>
                <span>

                    {% post_to_twitter  data.long_text  data.url  "twitter" %}
                </span>
            </button>

        </div>
        <div class="dropdown-item">
            <button class="button is-link is-outlined">
                <span class="icon is-small">
                    <i class="fab fa-envelope-square"></i>
                </span>
                <span>

                    {% send_email  data.subject  data.long_text  data.url  "email" %}
                </span>
            </button>

        </div>
        <div class="dropdown-item">
            <button class="button is-link is-outlined">
                <span class="icon is-small">
                    <i class="fab fa-reddit"></i>
                </span>
                <span>

                    {% post_to_reddit  data.long_text  data.url  "reddit" %}
                </span>
            </button>

        </div>

        <div class="dropdown-item">
            <button class="button is-link is-outlined">
                <span class="icon is-small">
                    <i class="fab fa-whatsapp"></i>
                </span>
                <span>
                    {% post_to_whatsapp  data.url  "whatsapp" %}
                </span>
            </button>

        </div>
        <div class="dropdown-item">
            <button class="button is-link is-outlined">
                <span class="icon is-small">
                    <i class="fab fa-telegram"></i>
                </span>
                <span>
                    {% post_to_telegram data.long_text data.url "en Telegram" %}
                </span>
            </button>
        </div>
    </div>
</div>