web/apps/contacto/urls.py
from django.conf.urls import url
from django.urls import path
# from django.contrib import admin
from apps.contacto.views import ContactoView, contacto_sent_view, status_task_contacto

app_name = 'contacto'

urlpatterns = [
    path('', ContactoView.as_view(), name='formulario'),
    path('exitoso/', contacto_sent_view, name='exitoso'),
    path("ajax/contacto/task=<str:task_id>",
         status_task_contacto,
         name="email-enviado"),
]

web/web/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('filer/', include('filer.urls')),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path('accounts/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('parametro/',
         include('apps.parametro.urls', namespace='parametro'),
         name='parametro'),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/apps/contacto/models.py
from django.db import models

# Create your models here.


class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=50)
    email = models.EmailField(max_length=354)
    tema = models.CharField(max_length=300)
    cuerpo = models.TextField()
    fecha_envio = models.DateTimeField(auto_now=True)

    class Meta:
        app_label = "contacto"
        verbose_name = "Contacto"
        verbose_name_plural = "Contactos"
        ordering = ('fecha_envio', 'nombre', 'email', )

    def __repr__(self):
        return json.dumps(self.__dict__)

    def __str__(self):
        return "%s -> %s :: %s" % (self.nombre, self.tema, self.fecha_envio)

web/apps/contacto/forms.py
from django.forms import ModelForm
from django import forms
from apps.contacto.models import Contacto
from apps.webmail.tasks import send_mail
from captcha.fields import CaptchaField


class ContactoForm(ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Contacto
        fields = ['nombre', 'telefono', 'email', 'tema', 'cuerpo', "captcha"]

    def send_usuario_email(self, *args, **kwargs):
        """
        kwargs keys => {from to subject body, template_info}
        template_info => {nivel_nombre nombre_completo fecha_inicio}
        """
        template = 'contacto/email_contacto.dj.html'
        opts = {
            'template_path':
            template,
            'template_info':
            dict(data_persona={
                key: value
                for key, value in kwargs.items() if key in self.fields
            }),
            'debug':
            True
        }
        kwargs.update(opts)
        fields = kwargs.get('fields')
        if fields:
            del kwargs['fields']
        try:
            send_mail.delay(fields, template, kwargs, debug=True)
        except Exception as e:
            raise e

    def send_admin_email(self, *args, **kwargs):
        """
        kwargs keys => {from to subject body, template_info}
        template_info => {data_persona}
        """
        template = 'contacto/email_admin_contacto.dj.html'
        opts = {
            'template_path':
            template,
            'template_info':
            dict(data_persona={
                key: value
                for key, value in kwargs.items() if key in self.fields
            }),
            'debug':
            True
        }
        kwargs.update(opts)
        fields = kwargs.get('fields')
        if fields:
            del kwargs['fields']
        try:
            send_mail.delay(fields, template, kwargs, debug=True)
        except Exception as e:
            raise e

web/apps/contacto/views.py
from celery.result import AsyncResult
from django.http import JsonResponse
from django.shortcuts import render
from .forms import ContactoForm
from django.views.generic import FormView
from django.views.generic import TemplateView
from django.conf import settings
from apps.home.views import menu_nav

# Create your views here.

ADMIN_EMAILS = getattr(settings, "ADMIN_EMAILS", None)
EMAIL_HOST_USER = getattr(settings, "EMAIL_HOST_USER", None)


class ContactoView(FormView):
    form_class = ContactoForm
    template_name = 'contacto/contacto.dj.html'

    def get_success_url(self):
        return reverse_lazy("contacto:exitoso")

    def get_context_data(self, *args, **kwargs):
        """
        Dado el nombre del proyecto en slug
        se consulta la información del proyecto
        para entregar la visualización relacionada a este mismo
        """
        kwargs = super().get_context_data(**kwargs)
        kwargs["menu_nav"] = menu_nav()
        return kwargs

    def post(self, request, *args, **kwargs):
        """
        Post modification
        """
        field_names = dict(
            zip(('tema', 'cuerpo', 'de', 'para'),
                ('subject', 'body', 'from', 'to')))
        form = ContactoForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            data = {
                'from': EMAIL_HOST_USER,
                'to': [cleaned_data.get('email', 'dpineda@uchile.cl')]
            }
            fields = {
                value: cleaned_data.get(key)
                for key, value in field_names.items()
            }
            cleaned_data.update(fields)
            cleaned_data.update(data)
            form.send_usuario_email(**cleaned_data)
            cleaned_data.update({'to': ADMIN_EMAILS})
            form.send_admin_email(**cleaned_data)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


def contacto_sent_view(request, *args, **kwargs):
    return render(request, 'contacto/exitoso.dj.html', context=kwargs)


def status_task_contacto(request, task_id):
    data = {}
    if request.is_ajax and request.method == "GET":
        task = AsyncResult(task_id)
        status = False
        success = False
        value = 200
        if task.status == "SUCCESS":
            status = task.result.get("status")
            success = True
            value = 400
        data = {'task_id': task_id, 'status': status, "success": success}
        return JsonResponse(data, status=value)
    else:
        return JsonResponse(data, status=200)

web/apps/contacto/templates/contacto/contacto.dj.html
<!-- llamadas principales -->
<!-- Extender base -->
{% extends 'base.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}
{% load widget_tweaks %}

{% block title %}
Contacto | {{SITE_NAME}}
{% endblock %}

{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'contacto:formulario'  %}">Contacto</a>
</li>
{% endblock breadcrumbs %}


{% block content_article %}
<div class="columns">
    <article class="contacto-form column">
        <h1 class="title">Contactar a {{SITE_NAME}}</h1>
        <div class="mdl-card__supporting-text">
            <form action="{% url 'contacto:formulario' %}" method="POST">
                {% csrf_token %}
                <!-- nombre -->
                <div class="field field_contacto">
                    <label class="label"
                           for="{{form.nombre.id_for_label}}">
                        {{form.nombre.label}}</label>
                    <div class="control">
                        {% render_field form.nombre class+="input" %}</div>

                    <span class="help is-invalid">{{ form.nombre.errors }}</span>
                </div>
                <!-- telefono -->
                <div class="field_contacto">
                    <label class="label"
                           for="{{form.email.id_for_label}}">
                        {{form.telefono.label}}</label>
                    <div class="control">
                        {% render_field form.telefono class+="input" %}
                    </div>
                    <span class="help is-invalid">{{ form.telefono.errors }}</span>
                </div>
                <!-- email -->
                <div class="field_contacto">
                    <label class="label"
                           for="{{form.email.id_for_label}}">
                        {{form.email.label}}</label>
                    <div class="control">
                        {% render_field form.email class+="input" %}</div>
                    <span class="help is-invalid">{{ form.email.errors }}</span>
                </div>
                <!-- tema -->
                <div class="field_contacto">
                    <label class="label"
                           for="{{form.tema.id_for_label}}">
                        {{form.tema.label}}</label>
                    <div class="control">
                        {% render_field form.tema class+="input" %}</div>
                    <span class="mdl-textfield__error">{{ form.tema.errors }}</span>
                </div>
                <!-- cuerpo -->
                <div class="field_contacto">
                    <label class="label"
                           for="{{form.cuerpo.id_for_label}}">
                        {{form.cuerpo.label}}</label>
                    <div class="control">
                        {% render_field form.cuerpo class+="textarea" %}</div>
                    <span class="help is-invalid">{{ form.cuerpo.errors }}</span>
                </div>
                {% include 'components/captcha.dj.html' with captcha=form.captcha %}

                <!-- send button -->

                <div class="control">
                    <button id="sendButton" class="button is-link is-fullwidth" type="submit">Enviar
                        mensaje</button>
                </div>

            </form></div>
    </article>

    <article class="column">
        <h2 class="title is-2">Otras formas de contactar
        </h2>
        <figure id="im_contact">
            <img src="{% static './home/img/icono-contacto.svg' %}">
        </figure>
        <p><i>La forma más directa de contactarnos es mediante
            nuestro correo electrónico</i></p>

        <b>{{CONTACT_EMAIL}}</b>

        <p>
            <a href="mailto:{{CONTACT_EMAIL}}">Escribenos</a> 
        </p>
    </article>

</div>


{% endblock content_article %}

{% block special_css %}
<link rel="stylesheet"
      type="text/css"
      href="{% static 'contacto/css/contacto.css' %}">
{% endblock %}


<!-- Añadir JS extra en footer -->
{% block footer_javascript %}

<script src="{% static 'js/captcha.js' %}">
</script>

{% endblock %}

web/apps/contacto/templates/contacto/email_admin_contacto.dj.html
{% load inlinecss %}
{% inlinecss "inscripcion/css/email.css" %}
<html>
    <body>
        <article>
            <h1>Nos han escrito mediante el formulario de contacto</h1>
            <ul>
                {% for key, value in data_persona.items %}
                <li>{{key}} -> {{value}}</li>
                {% endfor %}
            </ul>
        </article>
    </body>
</html>
{% endinlinecss %}

web/apps/contacto/templates/contacto/email_contacto.dj.html
{% load inlinecss %}
{% inlinecss "inscripcion/css/email.css" %}
<html>
    <body>
        <article>
            <h1>{{data_persona.nombre}}, hemos recibido tu email de contacto </h1>

            <p>Lo más pronto posible nos comunicaremos a tu email {{data_persona.email}}, o
                bien a tu teléfono {{data_persona.telefono}}</p>

            <p>Lo que nos escribiste es lo siguiente:</p>

            <table>
                <tr><td>Tema</td><td>{{data_persona.tema}}</td></tr>
                <tr><td>Cuerpo</td><td>{{data_persona.cuerpo}}</td></tr>
            </table>

        </article>
    </body>
</html>
{% endinlinecss %}

web/apps/contacto/templates/contacto/exitoso.dj.html
{% extends 'base.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}
{% load widget_tweaks %}

{% block title %}
Contacto Exitoso |Curso de Programación para Organizaciones Comunitarias
{% endblock %}

{% block content_article %}
<div class="mdl-grid">
    <div class="mdl-cell--3-offset"></div>
    <article class="pagina-articulo mdl-cell mdl-cell--6-col">
    <h1>¡Gracias!</h1>
    <p>Próntamente nos pondremos en contacto contigo</p>
    <div id="mensaje_status"></div>
    </article>
</div>
{% endblock content_article%}

{% block footer_javascript %}
<script>
 function getCookie(name) {
     var cookieValue = null;
     if (document.cookie && document.cookie !== '') {
         var cookies = document.cookie.split(';');
         for (var i = 0; i < cookies.length; i++) {
             var cookie = cookies[i].trim();
             // Does this cookie string begin with the name we want?
             if (cookie.substring(0, name.length + 1) === (name + '=')) {
                 cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                 break;
             }
         }
     }
     return cookieValue;
 }
 var csrftoken = getCookie('csrftoken');
 
 const task_code="{{task_id}}";
 const  url="ajax/contacto/task="+task_code;

 /* consultar cada .5 seg*/
 const periodo = 500;
 const id=setInterval(get_status_signup, periodo);

 function stop_ajax(){
     clearInterval(id)
 };
 
 function get_status_signup(){
     let xhr = new XMLHttpRequest();
     xhr.open('GET', url, true);
     xhr.onload = function status_reporte(event){
         let data_txt = xhr.responseText;
         let data_json = JSON.parse(data_txt);
	       let success = data_json["success"];

	       if (success) {
	           stop_ajax();
	       };

         if (xhr.readyState==4){
             if (xhr.status==400 && success){
		             /* Poner algo en html */
		             let mensaje =  document.getElementById("mensaje_status");
		             // cambio de mensaje
                 if (data_json["status"]===true){
                     let MSG = "Hemos enviado tu email de contacto";
                     mensaje.innerHTML = MSG;}
                 else{
                     mensaje.innerHTML = "No se pudo enviar email de activación, vuelve a intentarlo";
                 }

             }
             else{
                 console.log("Error al recibir", xhr.status)

             }
         }

     };
     
     var csrftoken = getCookie('csrftoken');
     xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
     xhr.setRequestHeader("X-CSRFToken", csrftoken);
     xhr.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
     xhr.send();
 }
 
</script>
{% endblock %}