web/apps/accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (AppAccountsView, RegistrarUsuario, activate,
                    activation_sent_view, status_task_signup, LoginView,
                    ProfileView, LogoutView, PasswordChangeView,
                    PasswordChangeDoneView, profile_update_field)
from django.urls import reverse, reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('', AppAccountsView.as_view(), name='application'),
    path('app', AppAccountsView.as_view(), name='application'),
    path('login/', LoginView.as_view(), name='login'),
    path(
        'logout',
        LogoutView.as_view(),  # not override template
        name='logout'),
    path('password_change',
         PasswordChangeView.as_view(
             template_name="registration/password_change.dj.html",
             extra_context={'menu': True}),
         name='password_change'),
    path('password_change/done',
         PasswordChangeDoneView.as_view(
             template_name="registration/password_change_done.dj.html",
             extra_context={'menu': True}),
         name='password_change_done'),
    path('password_reset',
         auth_views.PasswordResetView.as_view(
             template_name="registration/password_reset.dj.html",
             email_template_name="registration/password_reset_email.dj.html",
             html_email_template_name="registration/password_reset_email.dj.html",
             subject_template_name="registration/password_reset_subject.txt",
             success_url=reverse_lazy("accounts:password_reset_done"),
             extra_context={'menu': True}),
         name='password_reset'),
    path('password_reset/done',
         auth_views.PasswordResetDoneView.as_view(
             template_name="registration/password_reset_done.dj.html",
             extra_context={'menu': True}),
         name='password_reset_done'),
    path('password-reset/confirm/uidb64=<uidb64>/token=<token>',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.dj.html',
             success_url=reverse_lazy('accounts:password_reset_complete'),
             extra_context={'menu': True}),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/password_reset_complete.dj.html',
             extra_context={'menu': True}),
         name='password_reset_complete'),
    path("signup/", RegistrarUsuario.as_view(), name='signup'),
    path('activacion-enviada/task=<task_code>',
         activation_sent_view,
         name='activacion-enviada'),
    path('activar/uidb64=<uidb64>/token=<token>/', activate, name='activate'),
    path("ajax/status_task/task=<str:task_id>",
         status_task_signup,
         name="status_task"),
    path("perfil/", ProfileView.as_view(), name='profile'),
    path("perfil/usuario=<str:username>",
         ProfileView.as_view(),
         name='profile_user'),
    path("perfil/update_field/usuario=<str:username>",
         profile_update_field,
         name='profile_update_field'),
]

web/apps/home/urls.py
from django.conf.urls import url
from django.urls import path
# from django.contrib import admin
from apps.home import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('nosotros', views.NosotrosView.as_view(), name='nosotros'),
    path('aplicaciones', views.AppsView.as_view(), name='apps'),
    #path('proyecto', views.ProyectoView.as_view(), name='proyecto'),
    #path('contacto', views.ContactoView.as_view(), name='contacto'),
]

web/web/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.home.views import (page_not_found, bad_request, permission_denied,
                             server_error)

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('404/', page_not_found),
    path('403/', permission_denied),
    path('400/', bad_request),
    path('500/', server_error),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('filer/', include('filer.urls')),
    path('captcha/', include('captcha.urls'), name='captcha'),
    path('', include('apps.home.urls', namespace='home'), name='home'),
    path('pagina/',
         include('apps.pagina.urls', namespace='pagina'),
         name='pagina'),
    path('contacto/',
         include('apps.contacto.urls', namespace='contacto'),
         name='contacto'),
    path("admin_group/",
         include('apps.admin_group.urls', namespace='admin_group'),
         name='admin_group'),
    path('groups_manager/',
         include('groups_manager.urls', namespace='groups_manager'),
         name='groups_manager'),
    path('accounts/',
         include('apps.accounts.urls', namespace='accounts'),
         name='accounts'),
    path('proyecto/',
         include('apps.proyecto.urls', namespace='proyecto'),
         name='proyecto'),
    path('parametro/',
         include('apps.parametro.urls', namespace='parametro'),
         name='parametro'),
    path('martor/', include('martor.urls')),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/apps/accounts/views.py
import io
import json
import base64
from django.core.files.base import File
from django.core.files.base import ContentFile
from django.utils.text import slugify
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import views as auth_views
from celery.result import AsyncResult
from django.http import JsonResponse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic.edit import FormView
from django.views.generic import DetailView
from .tokens import account_activation_token
from django.http import Http404
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.urls import reverse, reverse_lazy
from .forms import RegistrarUsuarioForm
from django.conf import settings
from django.contrib.auth.models import User
from apps.home.views import menu_nav
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Profile, ProfileImage, PrincipalImageProfile
from pprint import pprint


ADMIN_EMAILS = getattr(settings, "ADMIN_EMAILS", [])
EMAIL_HOST_USER = getattr(settings, "DEFAULT_FROM_EMAIL", None)
SITE_URL = getattr(settings, "SITE_URL", "localhost")
SITE_NAME = getattr(settings, "SITE_NAME", "Curso de Programación")


# Create your views here.
class AppAccountsView(TemplateView):
    template_name = 'accounts/app.dj.html'


class RegistrarUsuario(FormView):
    form_class = RegistrarUsuarioForm
    template_name = 'registration/signup.dj.html'
    app_active = "Profile"

    def form_valid(self, form):
        fields = ('subject', 'body', 'from', 'to')
        user = form.save()
        user.refresh_from_db()
        acepta = form.cleaned_data.get('acepta')
        if acepta:
            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            user.profile.email = email
            user.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            # construcción de data email
            user_fields = dict(
                zip(fields, (
                    f"Registro en web de {SITE_NAME}",
                    "Registro exitoso!",
                    EMAIL_HOST_USER,
                    [email],
                )))
            opts = {'user': user, 'fields': user_fields, 'domain': SITE_URL}
            user_email = form.send_usuario_email(**opts)
            admin_fields = dict(
                zip(fields, (
                    f"Registro de nuevo usuario en web {SITE_NAME}",
                    "Se ha registrado una nueva persona!",
                    EMAIL_HOST_USER,
                    ADMIN_EMAILS,
                )))
            admin_opts = {
                'user': user,
                'fields': admin_fields,
                'domain': SITE_URL
            }
            form.send_admin_email(**admin_opts)
            self.opts = {"task_code": getattr(user_email, "id")}
            return super().form_valid(form)
        else:
            return super().form_invalid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('accounts:activacion-enviada', kwargs=self.opts)

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({
            'menu_nav': menu_nav,
            "app_active": self.app_active,
            "menu": True
        })
        return kwargs


def activation_sent_view(request, *args, **kwargs):
    return render(request,
                  'registration/activate_sent.dj.html',
                  context=kwargs)


def activate(request, uidb64, token):
    try:
        uid = int(base64.b64decode(uidb64.encode()))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # checking if the user exists, if the token is valid.
    if user and account_activation_token.check_token(user, token):
        # if valid set active true
        user.is_active = True
        # set signup_confirmation true
        user.profile.signup_confirmation = True
        user.save()
        login(request,
              user,
              backend='django.contrib.auth.backends.RemoteUserBackend')
        return redirect(reverse('home:index'))
    else:
        return render(request, 'registration/activacion_invalida.dj.html')


def status_task_signup(request, task_id):
    data = {}
    if request.is_ajax and request.method == "GET":
        task = AsyncResult(task_id)
        status = False
        success = False
        value = 200
        if task.status == "SUCCESS":
            status = task.result.get("status")
            success = True
            value = 400
        data = {'task_id': task_id, 'status': status, "success": success}
        return JsonResponse(data, status=value)
    else:
        return JsonResponse(data, status=200)


# Create your views here.
# accounts/login/ [name='login']
class LoginView(auth_views.LoginView):
    template_name = "registration/login.dj.html"
    app_active = "Profile"

    def get_success_url(self, *args, **kwargs):
        return reverse('accounts:profile_user',
                       kwargs={'username': self.request.user.username})

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        kwargs.update({
            'menu_nav': menu_nav,
            "app_active": self.app_active,
            "menu": True
        })
        return kwargs


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/profile.dj.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    app_active = "Profile"

    def get_context_data(self, *args, **kwargs):
        kwargs = super().get_context_data(**kwargs)
        place = self.request.user.profile.ubicacion.point
        print("Lugar usuario", self.request.user)
        print("Place->", place)
        default_position = {"lat": -33.447487,
                            'lon': -70.673676}
        if place:
            default_position = place
        mode = "_".join(sorted(default_position.keys()))
        kwargs.update({
            'menu_nav': menu_nav,
            "app_active": self.app_active,
            "menu": True,
            "map_params": {
                "maps": {
                    "modal": "map_modal",
                    "page": "map"
                },
                "editable": {
                    "modal": True,
                    "page": False
                },
                "geometria": {
                    "modal": "point",
                    "page": "point"
                },
                "position": {
                    "modal": default_position,
                    "page": default_position,
                },
                "mode": {
                    "modal": mode,
                    "page": mode,
                }
            }
        })
        return kwargs


# accounts/logout/ [name='logout']
class LogoutView(auth_views.LogoutView):
    next_page = reverse_lazy('home:index')


# accounts/password_change/ [name='password_change']
class PasswordChangeView(LoginRequiredMixin, auth_views.PasswordChangeView):
    template_name = "registration/cambio_password.dj.html"
    success_url = reverse_lazy('accounts:password_change_done')


# accounts/password_change/done/ [name='password_change_done']
class PasswordChangeDoneView(LoginRequiredMixin,
                             auth_views.PasswordChangeDoneView):
    template_name = "registration/cambio_password_lista.dj.html"


"""
Ajax calls
"""

from .functions import create_user_place

@csrf_exempt
def profile_update_field(request, *args, **kwargs):
    user_fields = {
        "username",
        "email",
        "first_name",
        "last_name",
    }
    profile_fields = {
        "first_name", "father_last_name", "mother_last_name", "email",
        "phonenumber", "bio", "ubicacion"
    }
    image_profile_fields = {"tag", "image"}
    new = False
    if request.is_ajax():
        data_dict = json.loads(request.body)
        user = User.objects.get(username=kwargs.get("username"))
        profile = user.profile
        # if field name from data in setsockopt
        all_changes = {}
        imageprofile = None
        if any(map(lambda k: k in data_dict, image_profile_fields)):
            imageprofile, new = ProfileImage.objects.get_or_create(
                tag=data_dict.get("tag", {}).get("value"))
        for key, data in data_dict.items():
            field_name = data.get("field_name")
            value = data.get("value")
            changes = {
                "field_name": field_name,
                "user": False,
                "profile": False,
                "from_user": "",
                "from_profile": "",
                "to": value
            }
            if field_name in user_fields:
                changes["from_user"] = getattr(user, field_name)
                setattr(user, field_name, value)
                user.save()
                changes["user"] = True
            if field_name in profile_fields:
                if field_name == 'phonenumber':
                    changes["from_profile"] = field_name
                if field_name == 'ubicacion':
                    """
                    Crear un nuevo lugar para el perfiles
                    entregar como resultado.
                    """
                    changes["from_profile"] = create_user_place(user, data)
                else:
                    changes["from_profile"] = getattr(profile, field_name)
                if field_name != "ubicacion":

web/apps/accounts/templates/accounts/app.dj.html
{% extends "accounts/base_login.dj.html" %}

{% block content_accounts %}
{% include 'accounts/main_ui.dj.html' %}
{% endblock content_accounts %}

web/apps/accounts/templates/accounts/base_login.dj.html
<!-- llamadas principales -->
<!-- Extender base -->
{% extends 'base.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}

<!-- css para detail protocol -->
{% block special_css %}
<link rel="stylesheet"
      type="text/css"
      href="{% static 'accounts/css/estilos.css' %}">
{% endblock %}

{% block title %}
Cuenta de Usuario|{{SITE_NAME}}
{% endblock %}

{% block breadcrumbs %}
{{block.super}}
<li class="is-active">
    Cuentas
</li>
{% endblock breadcrumbs %}



{% block content_article %}
<div class="tile is-ancestor">
<div class="tile is-parent is-2">
    <!--menú de acceso a las opciones de reporte general -->
    <div class="tile is-child box">
        <div class="sticky">
	          {% include 'accounts/main_menu.dj.html' %}
        </div>
    </div>
</div>

<article
    id="app_accounts"
    class="tile is-parent">
    <div class="tile is-child">
            <!--pantalla central con iconos -->
            {% block content_accounts %}
            {% endblock content_accounts %}
    </div>
</article>
</div>
{% endblock content_article %}

web/apps/accounts/templates/accounts/base_profile.dj.html
<!-- Extender base -->
{% extends 'base.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}

<!-- css para detail protocol -->
{% block special_css %}
<link rel="stylesheet"
      type="text/css"
      href="{% static 'accounts/css/estilos.css' %}">
{% endblock %}

{% block title %}
Perfil de Usuario|{{SITE_NAME}}
{% endblock %}


{% block breadcrumbs %}
{{block.super}}
<li>
    <a href="{% url 'accounts:profile_user' username=user.username %}">Perfil</a>
</li>
{% endblock breadcrumbs %}

{% block sidebar_left %}

{% endblock sidebar_left %}


{% block content_article %}
<div class="tile is-ancestor">
    <div class="tile is-parent is-3">
        <!--menú de acceso a las opciones de reporte general -->
        <div class="tile is-child box">
            <div class="sticky">
                {% include 'accounts/profile_menu.dj.html' %}
            </div>
        </div>
    </div>

    <article
        id="app_accounts"
        class="tile is-parent">
        <div class="tile is-child">
            <!--pantalla central con iconos -->
            {% block content_profile %}
            {% endblock content_profile %}
        </div>
    </article>
</div>
            <!--pantalla central con iconos -->
{% endblock content_article %}

web/apps/accounts/templates/accounts/card_login.dj.html
<div class="card">
    <div class="card-image">
        
    </div>
    <div class="card-content">
        <div class="content">
            <a
                class="login-button
                       button
                       is-rounded
                       is-success
                       is-medium
                       is-fullwidth"
                href="{% url 'accounts:login' %}"
                 alt="login">
                Ingresa</a>
            <a class="login-button
                      button
                      is-rounded
                      is-info
                      is-medium
                      is-fullwidth"
               href="{% url 'accounts:signup' %}"               
               alt="registro">Únete a la Comunidad</a>
        </div>        
    </div>
</div> 

web/apps/accounts/templates/accounts/main_menu.dj.html
<aside class="menu">
    <h1 class="menu-label">Cuenta de Usuario</h1>
    {% if not user.is_authenticated %}
    <ul class="menu-list">
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        <li><a href="{% url 'accounts:signup' %}">Crear usuario</a></li>
        <li><a href="{% url 'accounts:password_reset' %}">Reset Password</a></li>
    </ul>
    {% endif %}
    {% if user.is_authenticated %}
    <h1 class="menu-label">Administrar</h1>
    <ul class="menu-list">
        <li><a href="{% url 'admin_group:application' %}">Grupos de Admin</a></li>
    </ul>
    <h1 class="menu-label">Acciones</h1>
    <ul class="menu-list">
        <li><a href="{% url 'accounts:profile' %}">Perfil</a></li>
        <li><a href="{% url 'accounts:password_change' %}">Change Password</a></li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
    </ul>
        {% endif %}
</aside>

web/apps/accounts/templates/accounts/main_ui.dj.html
<section>
    <h1 class="title is-2">App de Cuentas de Usuario</h1>
    <p>En esta app puedes hacer lo siguiente:</p>
    <ol>
        <li>Login</li>
        <li>Crear cuenta</li>
        <li>Rescatar password</li>
        <li>Reset Password</li>
        <li>Ver perfil de usuario</li>
    </ol>
</section>

web/apps/accounts/templates/accounts/profile.dj.html
<!-- Extender base -->
{% extends 'accounts/base_profile.dj.html' %}
<!-- Permitir el uso de estaticos css js -->
{% load static %}
{% load thumbnail %}

<!-- css para detail protocol -->
{% block special_css %}
<link rel="stylesheet"
      type="text/css"
      href="{% static 'accounts/css/estilos.css' %}">
<link rel="stylesheet"
      type="text/css"
      href="{% static './geolands/dist/index.css' %}">
{% endblock %}

{% block content_profile %}
<!-- show profile info -->
<!-- imagen, nombres, email, teléfono, cursos (inscritos, aprobados, rechazaods)-->
<form class="tile is-vertical box">
    {% csrf_token %}
    <div class="tile is-ancestor">
        <div class="tile is-parent">
        <div class="tile is-child box">
            <h4 class="title is-4 has-text-centered">Imagen de Perfil</h4>
            <div class="tile is-child" >
                <div class="field">
                    <figure id="profile_image"  class="thumb_imagen profile has-text-centered">
                        {% thumbnail object.profile.profile_image.image "160x160" as im %}
                        <img src="{{ im.url }}" width="{{im.width}}"
                             height="{{im.height}}"
                             style="margin:{{im|margin:"200x200" }}"
                             id="img_perfil">
                        {% endthumbnail %}
                        {% include 'components/modal_image_select.dj.html' with param="image" image=object.profile.profile_image  %}
                </figure>
                </div>
                <button type="button" class="button is-info is-fullwidth"
                        onclick="update_image('image')">
                    Actualizar</button>
            </div>
        </div>
        </div>
        <div class="tile is-parent">
        <div class="tile is-child box">
            <h4 class="title is-4">Biografía</h4>
            <div class="field">
                <textarea type="textarea"
                          class="textarea"
                          id="bio_text"
                          row=15
                          name="bio"
                          readonly>{{object.profile.bio}}</textarea>
            </div>
            <div class="edit-bar">{% include 'components/edit_field.dj.html'  with row_id="bio_text"%}</div>
        </div>
        </div>
        </div>
        <div class="tile is-child box">
            <h4 class="title is-4">Información de Usuario</h4>
            <table class="table is-hoverable is-stripped is-fullwidth">
                <thead>
                    <th>Nombre</th>
                    <th>Valor</th>
                    <th>Acciones</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Nombre de usuario</td>
                        <td><input class="input" type="input"
                                   id="input_username" name="username"
                                   value="{{object.username}}" readonly></td>
                        <td class="edit-bar">{% include 'components/edit_field.dj.html' with row_id="input_username" %}</td>
                    </tr>
                    <tr>
                        <td>Nombre</td>
                        <td><input class="input" type="input" id="input_nombre" name="first_name"
                                   value="{{object.profile.first_name}}" readonly></td>
                        <td class="edit-bar">{% include 'components/edit_field.dj.html' with row_id="input_nombre" %}</td>
                    </tr>
                    <tr>
                        <td>Apellido Paterno</td>
                        <td><input class="input" type="input"
                                   id="input_apellido" name="father_last_name"
                                   value="{{object.profile.father_last_name}}" readonly></td>
                        <td class="edit-bar">{% include 'components/edit_field.dj.html' with row_id="input_apellido" %}</td>
                    </tr>
                    <tr>
                        <td>Apellido Materno</td>
                        <td><input class="input" type="input"
                                   id="input_apellido_materno" name="mother_last_name"
                                          value="{{object.profile.mother_last_name}}" readonly></td>
                        <td class="edit-bar">{% include 'components/edit_field.dj.html'  with row_id="input_apellido_materno"%}</td>
                    </tr>
                    <tr>
                        <td>
                            Correo Electrónico
                        </td>
                        <td><input class="input" type="input" id="email" name="email"
                                   value="{{object.email}}" readonly></td>
                        <td class="edit-bar">{% include 'components/edit_field.dj.html' with row_id="email"%}</td>
                    </tr>
                    <tr>
                        <td>Teléfono</td>
                        <td>
                            <input
                                class="input"
                                type="input"
                                id="phonenumber"
                                name="phonenumber"
                                value="{{object.profile.phonenumber}}" readonly></td>
                        <td class="edit-bar">{% include 'components/edit_field.dj.html'  with row_id="phonenumber"%}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="tile is-child box">
            <div class="columns">
                <h4 class="title column is-4 is-half">Ubicación</h4>
                <div class="column is-half">
            <button type="button" class="button is-info is-fullwidth"
                    onclick="update_place('ubicacion')" id="update_place_btn">
                Cambiar</button>
                </div>
            </div>
            <div class="tile is-child">
                <td><input class="input" type="input"
                           id="lugar" name="lugar"
                           value="{{object.profile.ubicacion}}" readonly></td>
            </div>

            <div id="map"></div>
        </div>
</form>
{% include 'components/modal_place.dj.html' with param="ubicacion"  %}
{% endblock content_profile %}

{% block footer_css %}
<style>
 #profile_image{
     height:200px;
 }
</style>
{% endblock %}
{% block footer_javascript %}
{{block.super}}
{{map_params|json_script:"map_params"}}
<script>
 let maps = {}
 window.maps = maps;
 window.username="{{user.username}}";
 window.update_url="{% url 'accounts:profile_update_field' user.username %}";
</script>
<!-- enable profile fns -->

<script defer src="{% static 'profile/dist/profile_load.js' %}"></script>
{% endblock %}

web/apps/accounts/templates/accounts/profile_manu.dj.html
<section>
    <h1 class="title is-3">Accounts</h1>
    <ul>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        <li><a href="{% url 'accounts:signup' %}">Crear usuario</a></li>
        <li><a href="{% url 'accounts:password_reset' %}">Reset Password</a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <li>Profile</li>
        <li><a href="{% url 'accounts:password_change' %}">Change Password</a></li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
        {% endif %}
    </ul>
</section>

web/apps/accounts/templates/accounts/profile_menu.dj.html
<aside class="menu sticky">
    {% if user.is_authenticated %}
    <h1 class="menu-label">Perfil de Usuario</h1>
    <h1 class="menu-label">Cuenta</h1>
    <ul class="menu-list">
        <li>
            <a href="{% url 'accounts:profile_user' username=user.username %}">
                Perfil</a></li>
        <li><a href="{% url 'proyecto:application' %}">Mis Proyectos</a></li>
        <li><a href="">Inscripciones</a></li>
    </ul>
    {% if user.is_superuser %}
    <h1 class="menu-label">Grupos</h1>
    <ul class="menu-list">
        <li><a href="{% url 'groups_manager:groups_manager' %}">
            Administración de Grupos</a></li>
    </ul>
    {% endif %}
    <h1 class="menu-label">Administrar</h1>
    <ul class="menu-list">
        <li><a href="{% url 'accounts:profile_user' username=user.username %}">Perfil</a></li>
        {% if user.is_superuser %}
        <li><a href="{% url 'admin:index' %}">Administrar</a></li>
        {% endif %}
        <!-- check if user CAN manage projects -->
        <li><a href="">Proyectos</a></li>
        <li><a href="{% url 'accounts:password_change' %}">Change Password</a></li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
    </ul>
    {% endif %}
</aside>